import js from '@eslint/js'
import pluginVue from 'eslint-plugin-vue'

export default [
  js.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['**/*.{js,vue}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        AbortController: 'readonly',
        Blob: 'readonly',
        CustomEvent: 'readonly',
        EffectScope: 'readonly',
        EventSource: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        WebSocket: 'readonly',
        acceptHMRUpdate: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        computed: 'readonly',
        console: 'readonly',
        createApp: 'readonly',
        createPinia: 'readonly',
        customRef: 'readonly',
        defineAsyncComponent: 'readonly',
        defineComponent: 'readonly',
        defineStore: 'readonly',
        document: 'readonly',
        effectScope: 'readonly',
        fetch: 'readonly',
        getActivePinia: 'readonly',
        getComputedStyle: 'readonly',
        getCurrentInstance: 'readonly',
        getCurrentScope: 'readonly',
        h: 'readonly',
        history: 'readonly',
        inject: 'readonly',
        isProxy: 'readonly',
        isReactive: 'readonly',
        isReadonly: 'readonly',
        isRef: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        mapActions: 'readonly',
        mapGetters: 'readonly',
        mapState: 'readonly',
        mapStores: 'readonly',
        mapWritableState: 'readonly',
        markRaw: 'readonly',
        navigator: 'readonly',
        nextTick: 'readonly',
        onActivated: 'readonly',
        onBeforeMount: 'readonly',
        onBeforeRouteLeave: 'readonly',
        onBeforeRouteUpdate: 'readonly',
        onBeforeUnmount: 'readonly',
        onBeforeUpdate: 'readonly',
        onDeactivated: 'readonly',
        onErrorCaptured: 'readonly',
        onMounted: 'readonly',
        onRenderTracked: 'readonly',
        onRenderTriggered: 'readonly',
        onScopeDispose: 'readonly',
        onServerPrefetch: 'readonly',
        onUnmounted: 'readonly',
        onUpdated: 'readonly',
        onWatcherCleanup: 'readonly',
        provide: 'readonly',
        reactive: 'readonly',
        readonly: 'readonly',
        ref: 'readonly',
        requestAnimationFrame: 'readonly',
        resolveComponent: 'readonly',
        screen: 'readonly',
        sessionStorage: 'readonly',
        setActivePinia: 'readonly',
        setInterval: 'readonly',
        setMapStoreSuffix: 'readonly',
        setTimeout: 'readonly',
        shallowReactive: 'readonly',
        shallowReadonly: 'readonly',
        shallowRef: 'readonly',
        storeToRefs: 'readonly',
        toRaw: 'readonly',
        toRef: 'readonly',
        toRefs: 'readonly',
        toValue: 'readonly',
        triggerRef: 'readonly',
        unref: 'readonly',
        useAttrs: 'readonly',
        useCssModule: 'readonly',
        useCssVars: 'readonly',
        useId: 'readonly',
        useLink: 'readonly',
        useModel: 'readonly',
        useRoute: 'readonly',
        useRouter: 'readonly',
        useSlots: 'readonly',
        useTemplateRef: 'readonly',
        watch: 'readonly',
        watchEffect: 'readonly',
        watchPostEffect: 'readonly',
        watchSyncEffect: 'readonly',
        window: 'readonly'
      
      }
    },
    rules: {
      // 布局类规则交给 Prettier，ESLint 不重复管格式
      'vue/multi-word-component-names': 'off',
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-quotes': 'off',
      'vue/html-closing-bracket-spacing': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/mustache-interpolation-spacing': 'off',
      'vue/first-attribute-linebreak': 'off',
      'vue/attributes-order': 'off',
      'vue/attribute-hyphenation': 'off',
      'vue/v-on-event-hyphenation': 'off',
      // 历史代码存量问题，先降级为警告逐步清理
      'vue/no-mutating-props': 'warn',
      'vue/no-side-effects-in-computed-properties': 'warn',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-console': 'off'
    }
  },
  {
    ignores: ['dist/**', 'node_modules/**', '*.config.js', 'bin/**']
  }
]
